### ISSUE TITLE
ExplosionEvent.Detonate doesn't seem to be fired

### ISSUE THREAD

**Issue by MineMaarten** [INpureProjects/CreeperCollateral#2]
Someone reported an issue on PneumaticCraft's issue tracker:
https://github.com/MineMaarten/PneumaticCraft/issues/451

After breakpointing I discovered that CreeperCollateral doesn't seem to be firing the ExplosionEvent.Detonate PneumaticCraft is relying on:
https://github.com/MineMaarten/PneumaticCraft/blob/master/src/pneumaticCraft/common/EventHandlerPneumaticCraft.java#L86

**Comment by denoflionsx** [comment]
That event probably didn't exist when CC was made for 1.7.10. The class patching will have to be remade.

**Comment by MineMaarten** [comment]
yes, it's a fairly recent addition to forge yes. But this is a reminder in case you missed the addition :P

**Comment by denoflionsx** [comment]
If you would please give this maven build a try. It should resolve the issue. Let me know and I'll push it to Curse.

http://files.inpureprojects.info/maven/info/inpureprojects/CreeperCollateral/%5B1.7.10%5D1.0.0B3-15/
